name: Build and deploy Node.js app to Azure Web App - testbs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Match Azure runtime

      - name: Install dependencies
        run: npm install

      - name: Build application (if applicable)
        run: npm run build --if-present

      - name: Run tests (optional)
        run: npm test || echo "Tests failed but continuing deployment"

      - name: Archive production artifacts
        run: zip -r release.zip . -x "**node_modules/**" "**.git/**" "**.github/**"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 'f53da4b4-2947-4747-91c7-07e8beaab046'
          tenant-id: 'e78893e0-852e-4f4d-87c5-5ed00fdd7a27'
          subscription-id: '166e9f9d-f1e6-457b-951e-1e35c6fa492f'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'testbs'
          slot-name: 'Production'
          package: release.zip # Deploying the zip file
